name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Сборка проекта с Maven
        run: mvn clean package

      - name: Сборка и пуш Docker-образа
        working-directory: core
        run: |
          docker build --build-arg JAR_FILE=target/matreshka-core-1.0-SNAPSHOT.jar -t matreshka-erp:latest .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка новой версии в Kubernetes
        working-directory: deploy
        run: |
          helm upgrade -i matreshka-erp .
