name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend
        run: mvn clean package

      - name: Build backend docker image
        working-directory: core
        run: |
          docker build --build-arg JAR_FILE=target/matreshka-core-1.0-SNAPSHOT.jar -t matreshka-backend:latest .

  build-frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend
        working-directory: frontend
        run: |
          source ~/.zshrc
          npm install
          npm run build

      - name: Build frontend docker image
        working-directory: frontend
        run: |
          docker build . -t matreshka-frontend:latest

  deploy:
    runs-on: self-hosted
    needs:
      - build-backend
      - build-frontend
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка новой версии в Kubernetes
        working-directory: deploy
        run: |
          helm upgrade -i matreshka-erp .
          kubectl rollout restart deployment/matreshka-erp
